"""models minor changes

Revision ID: cfd548b48dba
Revises: 30a917aafe5c
Create Date: 2025-11-13 16:10:54.049988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd548b48dba'
down_revision: Union[str, None] = '30a917aafe5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy import inspect

def upgrade() -> None:
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('document_requests')]

    with op.batch_alter_table('document_requests', schema=None) as batch_op:
        if 'message_id' not in columns:
            batch_op.add_column(sa.Column('message_id', sa.Integer(), nullable=True))
            batch_op.create_unique_constraint(None, ['message_id'])
            batch_op.create_foreign_key(None, 'messages', ['message_id'], ['id'])

        if 'deadline' not in columns:
            batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))




def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_requests', type_='foreignkey')
    op.drop_constraint(None, 'document_requests', type_='unique')
    op.drop_column('document_requests', 'deadline')
    op.drop_column('document_requests', 'message_id')
    # ### end Alembic commands ###
